### PR TITLE
Updated gitignore - no bin files

### PR DESCRIPTION
**Pull request by pgavigan**
Updated gitignore to prevent bin files from being committed to the repo in error.

### CODE REVIEW

**Comment by ntartania** [comment]
sounds good to me.
I'm not 100% sure we need the gitignore file itself in version control since we may have specific things in it that say what we don't want to commit... but I guess it can be the superset of all our files to be ignored.

**Comment by esfandia** [comment]
As long as we're careful what we "git add", and that peer review catches accidental additions, we shouldn't need this. I have plenty of files that are untracked by git, I don't think that's a problem. 

Having said that, I don't think this .gitignore is doing anything harmful. I believe most projects do share and track their .gitignore. I don't want to block this if you feel this is necessary.

**Comment by pgavigan** [comment]
I see your comments that this appears to be an OK pull request, but neither of you has actually issued an approval of it yet. Please approve the pull request.

**Comment by pgavigan** [comment]
I'm going to merge this branch. When I rebase, do I rebase master onto ignoreBin or do I rebase ignoreBin onto master? It isn't clear which way I'm supposed to do that.

**Comment by ntartania** [comment]
rebase ignorebin on master

You want to do this before merging the PR.
steps:
1 git pull origin master (assuming github repo is called origin)
2 git checkout ignorebin
3 git rebase master
4 git push origin ignorebin
5 see it on github and merge it.

**Pull request merged**
