### PR TITLE
 fix flickering

### PR DESCRIPTION
**Pull request by ntartania**
just a quick change to remove the annoying flicker
(removed a "repaint()" commandin marsenv.java)

@esfandia 
@pgavigan 
@ntartania -> this is me but I don't appear as the commiter because I haven't fixed my id in my local git

### CODE REVIEW

**Comment by pgavigan** [comment]
I'm going to close this pull request and implement a check using System.getProperty("os.name") to verify if the OS is Windows. If windows, then don't repaint, else repaint. Then I'll try a new pull request and see if it works for everyone.

**Comment by pgavigan** [comment]
I have implemented a check -> now if the OS is Windows 10 it will not repaint. I recommend everyone check their configuration and approve this pull request if the flicker issue is resolved. If not, I suggest you close this pull request and modify it to include you OS in the check.

**Comment by esfandia** [comment]
Didn't Alan experience the flickering on Linux?

**Comment by ntartania** [comment]
yes... I'll add a linux case to the check.

Le lun. 22 oct. 2018 à 17:21, Babak Esfandiari <notifications@github.com> a
écrit :

**Comment by ntartania** [comment]
Now fixed on Linux as well.

**Comment by ntartania** [comment]
@pgavigan @esfandia 
Please check if this now works for you and if so :+1:

**Pull request merged**
