### PR TITLE
Introducing Gradle

### PR DESCRIPTION
**Pull request by MikeVezina**
I'd suggest pulling this branch and looking at the code (and testing it) through an IDE/Editor rather than use GitHub since all the directories & file locations have been changed and it'll be difficult to sift through on GitHub's preview. Please follow the Wiki instructions [here](https://github.com/NMAI-lab/SAVI/wiki/Project-&-Gradle-Setup) on how to do set up the gradle project, and make sure that everything runs as expected.

The desired functionality (gradle) has been implemented, but in the process there were a few other changes that needed to be done to conform to the ideals of gradle. This includes:

1. Loading non-java files (.asl and images) from a 'resources' directory (I created a resource manager 'savi/util/ResourceManager' for the purpose of loading resource files and creating output files). This also allows us to pull resource files from within the JAR file too (we no longer have to copy the images to a directory beside the JAR file, yay!).

2. Output files from the simulation are now organized into an output directory so that they do not flood the project directory.

3. Unit tests are now under the test directory

4. I have removed the debugging directory, since this directory is static and is not part of our mainstream development, it should either go in it's own repository or be contained in a zip file and can be downloaded through a link in our Wiki.

Here are some issues/concerns that I have (they are in the process of being fixed and/or tested):
- [x] Do internal actions load correctly? 
- [x] Jar creation is done correctly (all dependencies, and tested on mac & windows)

- [x] I have already done a bit of package clean-up but I think that a few more packages need to be re-organized. I'm thinking this might be better in another PR, but since I'm here messing with the packages already, it might be better to just do it in one shot. Any objections or suggestions for re-organizing the packages?

Please let me know your thoughts / opinions.

### CODE REVIEW

**Comment by pgavigan** [comment]
A few preliminary comments. Note, I have not yet tried to set up a project nor have I tried to run anything yet.

- Generally this looks really good! I like the wiki explanation.
- I like the idea of doing package cleanup now
- I think we need to have the option of building just the control station, just the simulation, or both.

I'll take a deeper dive in a bit.

**Comment by pgavigan** [comment]
Here is an error message I get when trying to build the project with Eclipse:


FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\patrickgavigan\Documents\GitHub\SAVI\build.gradle' line: 36

* What went wrong:
A problem occurred evaluating root project 'SAVI'.
> Could not find method application() for arguments [build_bhdjlf8p90cp5undm9infh3dj$_run_closure4@62e02363] on root project 'SAVI' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 5s

**Comment by pgavigan** [comment]
Another observation, the agent debugger is missing. We will need to preserve this functionality somewhere.

**Comment by esfandia** [comment]
Congrats for making this happen! I'll try it out ASAP.

**Pull request merged**
