### PR TITLE
Gui experiment

### PR DESCRIPTION
**Pull request by pgavigan**
This is a wip PR for the command GUI. It has a number of buttons with hard coded commands for the agents. These commands are sent as broadcast messages.

There are three commands that now have these hard coded buttons: followTarget, patrol, and sendTelemetry. These buttons are implemented and send the appropriate messages to all agents. Note, there is a need for some modification to the agent behaviour in order for them all to work properly (especially patrol and sendTelemetry). These modifications are being addressed in parallel in the behaviourDebug branch.

Feedback is requested specifically for button layout and functionality. For example, are there other buttons that we need? Are there buttons here that we don't need? Is there a better layout for these buttons?

### CODE REVIEW

**Comment by cruizm** [comment]
What is the objective of the Achieve Button?
I have also noticed that the "box", where the telemetry messages are displayed, has disappeared.

**Comment by pgavigan** [comment]
> What is the objective of the Achieve Button?
> I have also noticed that the "box", where the telemetry messages are displayed, has disappeared.

The achieve button is the old submit button that Alan had put there before. It sends whatever is written in the text box above it as an achieve message.

As for the telemetry box going away... oops. :) I'm still a bit rusty with Java Swing. I'll try to fix that shortly :)

**Comment by esfandia** [comment]
- for the layout, to handle adding more widgets and to organize them better, consider using JPanel. It's just an invisible widget you use to organize other widgets inside. So you could populate a panel with buttons, then just add that panel to the NORTH (or wherever) of the JFrame. In that JPanel you could use a BorderLayout, or any other layout that makes sense to you. For buttons, maybe a GridLayout is a better fit.

- for functionality, this is something you should discuss with Jeremy... Other than the canned buttons, I think having a graphical view of the telemetry, ideally on the same map as the sim, would be ideal. Not sure how one could embed Processing stuff in a Swing widget, but it should be possible.

- in terms of coding style, one improvement on the code you have would be to eliminate the if... then... else on the button labels, and instead use lambda notation to embed the function call directly in the addActionListener(). For example, if you have a single method called followTarget(), your  followTargetButton.addActionListener(this) code simply becomes followTargetButton.addActionListener(e ->followTarget()) and you don't need to do anything in the actionPerformed() block. If this isn't clear, see this link for example: https://www.codejava.net/java-core/the-java-language/java-8-lambda-listener-example

**Comment by pgavigan** [comment]
More progress has been made on this branch. A few noteworthy items:

- There is now a layout of buttons. It isn't quite how I designed it (I'm not great with GUI yet) and would appreciate a hand polishing it up.

- There is now a TelemetryFetcher class that spins off a new thread that requests telemetry from the agents at a set period. There is a button in the gui that sets this period. Soon it will set the period based on the value in a text box that I will make in my next iteration.

- I have seperated the gui from the underlying implementation of the control station logic. I plan to move to lambda notation in a later iteration.

- A possible later iteration will include a map window that displays the agents (based on their telemetry) and reported threats. I am unsure how I will implement this and am open to suggestions.

**Comment by pgavigan** [comment]
Even more progress! The layout for the buttons and text boxes is pretty much what I was going for now. All the buttons and text boxes work as designed (including setting the period for the telemetry fetch).

Next: Lambda notation for the events.

After that: visualization of the telemetry on a 'map' (if I can come up with an easy way to do that)

**Comment by pgavigan** [comment]
Lambda notation is done and all control station functionality currently implemented works!

Next: display window?

**Comment by ntartania** [comment]
I just ran this branch and the GUI appears strange, perhaps because my screen is fairly small.
Screen Shot 2019-04-27 at 3 38 46 PM

**Comment by ntartania** [comment]
I don't really know what to do with this GUI....

**Comment by pgavigan** [comment]
It occurs to me that I never provided my final explanation about this PR, sorry about that. The GUI provides several buttons for commanding the UxVs. This GUI is a demo program for assisting the development of more sophisticated control stations for UxVs. In addition to the GUI, there are classes for parsing agent messages as well as methods for requesting telemetry at regular intervals. Also included are buttons for starting the missions of the different UxVs. More details on how to use the GUI are below.

Here is the intended outcome of this PR:

1. The UxVs don't have any missions and are idle when the simulation starts.
2. There are several buttons in the GUI. At the top there are buttons for telemetry. You have 2 options, either to select a single telemetry item, which sends a single request to all UxVs for telemetry. Alternatively, you can enter a value in the textbox (in ms) to specify the period at which you want regular telemetry to be sent. The console proxy will then ping the UxVs at that period for telemetry.
3. There are two mission buttons: Patrol and Follow Target. Clocking each of these will start the patrol mission (for the UAV) and the follow target mission (for the UxVs). After clicking these buttons you will see the agents start to turn, move, fly, ect.
4. All messages are displayed to the GUI. This includes the telemetry (from points 1 and 2) as well as notices about threats (resulting from point 3). These are displayed as raw messages in the smaller window on the bottom on the right as well as parsed (more human readable messages) in the larger panel on the left.

**Comment by pgavigan** [comment]
Also, please note that this PR was rebased on top of the branch for PR #151, so there will be overlap with this PR until that branch is merged.

**Comment by pgavigan** [comment]
> I just ran this branch and the GUI appears strange, perhaps because my screen is fairly small.
> Screen Shot 2019-04-27 at 3 38 46 PM

I suspect that the screen is out of room. I developed on a large screen. I may need to make the GUI window smaller (although I'm not a GUI expert).

**Comment by pgavigan** [comment]
Here is the documentation I delivered with this code to the client.

[SupportDocumentation.pdf](https://github.com/NMAI-lab/SAVI/files/3149429/SupportDocumentation.pdf)

**Pull request merged**
